[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["rm -f package-lock.json && npm install --ignore-scripts"]

[phases.build]
cmds = ["npx nuxt prepare", "npm run build"]

[start]
cmd = "npm run db:migrate && node .output/server/index.mjs"
