[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
cmds = ["npm cache clean --force", "rm -f package-lock.json", "npm pkg delete scripts.postinstall", "npm install"]

[phases.build]
cmds = ["npx nuxt prepare", "npm run build"]

[start]
cmd = "npm run db:migrate && node .output/server/index.mjs"
